# Generated by Django 4.2.23 on 2025-08-17 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaduanAsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ktp', models.URLField(blank=True, null=True)),
                ('jawaban', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PengaduanAsingArsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ktp', models.URLField(blank=True, null=True)),
                ('tanggal_arsip', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuketRekKelTani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('ktp', models.CharField(max_length=50)),
                ('ttl', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('namawbp', models.CharField(max_length=255)),
                ('hubungan', models.CharField(max_length=100)),
                ('tanggal_kunjungan', models.DateField()),
                ('jam_kunjungan', models.TimeField()),
                ('jenis_kunjungan', models.CharField(max_length=50)),
                ('pengikut_laki', models.IntegerField(default=0)),
                ('pengikut_perempuan', models.IntegerField(default=0)),
                ('pengikut_anak', models.IntegerField(default=0)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('barang_bawaan', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('review', 'Proses Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='review', max_length=20)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=200)),
                ('ktp', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanPengaduanAsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dijawab_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_set', to='dashboard.pengaduanasing')),
            ],
        ),
        migrations.CreateModel(
            name='IjinLuarBiasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaju', models.CharField(max_length=150)),
                ('ktp_pengaju', models.CharField(max_length=50)),
                ('alamat_pengaju', models.TextField()),
                ('hubungan', models.CharField(max_length=100)),
                ('nama_wbp', models.CharField(max_length=150)),
                ('register_wbp', models.CharField(max_length=50)),
                ('alasan', models.TextField()),
                ('tanggal_ijin', models.DateField()),
                ('durasi', models.IntegerField(help_text='Dalam jam')),
                ('dokumen_ktp_kk', models.FileField(blank=True, null=True, upload_to='ilb')),
                ('dokumen_pernyataan', models.FileField(blank=True, null=True, upload_to='ilb')),
                ('dokumen_keterangan_desa', models.FileField(blank=True, null=True, upload_to='ilb')),
                ('status', models.CharField(choices=[('review', 'Proses Review'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='review', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BantuanHukum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaju', models.CharField(max_length=150)),
                ('ktp_pengaju', models.CharField(max_length=50)),
                ('alamat_pengaju', models.TextField()),
                ('hubungan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('pekerjaan_pengaju', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_wbp', models.CharField(max_length=150)),
                ('blok_wbp', models.CharField(blank=True, max_length=50, null=True)),
                ('pasal', models.CharField(blank=True, max_length=100, null=True)),
                ('lama_hukuman', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori_permasalahan', models.CharField(choices=[('pidana', 'Pidana'), ('perdata', 'Perdata'), ('narkotika', 'Narkotika'), ('korupsi', 'Korupsi'), ('lainnya', 'Lainnya')], max_length=50)),
                ('kronologi', models.TextField()),
                ('jenis_bantuan', models.CharField(max_length=200)),
                ('dokumen_ktp_kk', models.FileField(blank=True, null=True, upload_to='bantuan_hukum/')),
                ('dokumen_surat_kuasa', models.FileField(blank=True, null=True, upload_to='bantuan_hukum/')),
                ('dokumen_sktm', models.FileField(blank=True, null=True, upload_to='bantuan_hukum/')),
                ('dokumen_putusan', models.FileField(blank=True, null=True, upload_to='bantuan_hukum/')),
                ('dokumen_lainnya', models.FileField(blank=True, null=True, upload_to='bantuan_hukum/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
