# Generated by Django 4.2.23 on 2025-08-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dokumenintegrasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengikut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('kategori', models.CharField(choices=[('laki', 'Laki-laki'), ('perempuan', 'Perempuan'), ('anak', 'Anak-anak')], max_length=20)),
                ('suket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengikut', to='dashboard.suketrekkeltani')),
            ],
        ),
    ]
