# Generated by Django 4.2.23 on 2025-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pengikut'),
    ]

    operations = [
        migrations.AddField(
            model_name='suketrekkeltani',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
