# Generated by Django 4.2.23 on 2025-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_suketrekkeltani_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_tambah_surat', models.BooleanField(default=True)),
            ],
        ),
    ]
