# Generated by Django 4.2.23 on 2025-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_pengaturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suketrekkeltani',
            name='barang_bawaan',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
