# Generated by Django 4.2.23 on 2025-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_suketrekkeltani_barang_bawaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suketrekkeltani',
            name='barang_bawaan',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='suketrekkeltani',
            name='jenis_kunjungan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suketrekkeltani',
            name='ktp',
            field=models.CharField(max_length=100),
        ),
    ]
