# Generated by Django 4.2.23 on 2025-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_suketrekkeltani_barang_bawaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suketrekkeltani',
            name='telepon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
