# Generated by Django 4.2.23 on 2025-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_beritaketahananpangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijinluarbiasa',
            name='jenis_izin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ijinluarbiasa',
            name='durasi',
            field=models.IntegerField(help_text='Dalam hari'),
        ),
        migrations.AlterField(
            model_name='ijinluarbiasa',
            name='register_wbp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
