# Generated by Django 4.2.23 on 2025-08-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ijinluarbiasa_jenis_izin_alter_ijinluarbiasa_durasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijinluarbiasa',
            name='dokumen_kematian_rt',
            field=models.FileField(blank=True, null=True, upload_to='ilb'),
        ),
        migrations.AddField(
            model_name='ijinluarbiasa',
            name='dokumen_sakit',
            field=models.FileField(blank=True, null=True, upload_to='ilb'),
        ),
        migrations.AddField(
            model_name='ijinluarbiasa',
            name='dokumen_waris',
            field=models.FileField(blank=True, null=True, upload_to='ilb'),
        ),
        migrations.AlterField(
            model_name='ijinluarbiasa',
            name='jenis_izin',
            field=models.CharField(blank=True, choices=[('menikah', 'Menikah'), ('wali_nikah', 'Wali Nikah'), ('sakit', 'Menjenguk Keluarga Sakit'), ('meninggal', 'Meninggal'), ('waris', 'Pembagian Waris')], max_length=100, null=True),
        ),
    ]
